const constants = {
  FETCH_SURVEY: 'FETCH_SURVEY',
  EDIT_SURVEY: 'EDIT_SURVEY',
  PREVIEW_SURVEY: 'PREVIEW_SURVEY',
  SUBMIT_SURVEY: 'SUBMIT_SURVEY',
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
};

export default constants;
